from django.db import models, IntegrityError
from django.db.models.signals import post_save

from . import AUTH_USER_MODEL, Actor, UserActorOwnership
from django.utils.crypto import get_random_string

__author__ = 'Jailbreaker'


class UserProfile(models.Model):
    """
    User profile - Anything that is part of the user definition an is not in the PUser model comes here.
    """

    """
    FK to User
    """
    user = models.OneToOneField(
        to=AUTH_USER_MODEL,
        related_name='profile',
        primary_key=True,
        null=False,
        blank=False
    )

    """
    Personal user crypto address -- to send money to
    """
    crypto_address = models.CharField(
        # verbose_name='DOGE, bitcoin... address',
        max_length=50,
        blank=True
    )

    pin = models.CharField(
        verbose_name='Personal PIN',
        max_length=10,
        blank=True
    )

    balance_i = models.FloatField(verbose_name='Investment balance', default=0)
    balance_w = models.FloatField(verbose_name='Withdrawal balance', default=0)

    balance_coins = models.FloatField(default=0)

    """
    Who brought this user into the game
    """
    referrer = models.ForeignKey(
        to=AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='referrals',
    )

    """
    id to use for referral links. generated by the game
    """
    referral_id = models.CharField(
        max_length=30,
        unique=True,
        null=False,
        blank=False
    )

    """
    Last time coins were collected
    """
    last_coin_collection_time = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'UserProfile'

    def __unicode__(self):  # __str__ on python 3
        return self.user.get_username()
        # return 'UserProfile'


def create_userprofile(sender, instance, created, **kwargs):
    if created:
        print 'Creating userporofile for', instance
        up, created = UserProfile.objects.get_or_create(user=instance)
        up.pin = get_random_string(6)

        while True:
            # generate referral_id
            up.referral_id = get_random_string(length=12)
            try:
                up.save()
                break  # generated referral_id is unique and user profile got saved
            except IntegrityError:
                continue  # referral_id is not unique, try again

post_save.connect(create_userprofile, sender=AUTH_USER_MODEL)