from django.db import models
from django.conf import settings

__author__ = 'Jailbreaker'


AUTH_USER_MODEL = getattr(settings, "AUTH_USER_MODEL", "auth.User")


class UserProfile(models.Model):
    """
    User profile - Anything that is part of the user definition an is not in the PUser model comes here.
    """

    """
    FK to User
    """
    user = models.OneToOneField(
        to=AUTH_USER_MODEL,
        related_name='profile',  # TODO userprofile ?
        primary_key=True,
        null=False,
        blank=False
    )

    """
    Personal user crypto address -- to send money to
    """
    crypto_address = models.CharField(
        # verbose_name='DOGE, bitcoin... address',
        max_length=50,
        blank=True
    )

    pin = models.CharField(
        verbose_name='Personal PIN',
        max_length=10,
        null=True,
        blank=True
    )

    balance_i = models.FloatField(verbose_name='Investment balance', default=0)
    balance_w = models.FloatField(verbose_name='Withdrawal balance', default=0)

    balance_coins = models.FloatField(default=0)

    """
    Who brought this user into the game
    """
    referrer = models.ForeignKey(
        to=AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='referrals',
    )

    """
    id to use for referral links. generated by the game
    """
    referral_id = models.CharField(
        max_length=30,
        unique=True,
        null=False,
        blank=False
    )

    """
    Last time coins were collected
    """
    last_coin_collection_time = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'UserProfile'

    def __unicode__(self):  # __str__ on python 3
        return self.user.get_username()
        # return 'UserProfile'

